// <auto-generated />
using System;
using CoffeeShop.DAO.Impl.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoffeeShop.DAO.Impl.Migrations
{
    [DbContext(typeof(CoffeeShopAppContext))]
    [Migration("20200526222850_init3")]
    partial class init3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoffeeShop.DAO.Impl.DAO.DrinkDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MachineDAOId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MachineDAOId");

                    b.ToTable("DrinkDAOs");
                });

            modelBuilder.Entity("CoffeeShop.DAO.Impl.DAO.IngredientDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IngredientDAOs");
                });

            modelBuilder.Entity("CoffeeShop.DAO.Impl.DAO.MachineDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("MachineDAOs");
                });

            modelBuilder.Entity("CoffeeShop.DAO.Impl.DAO.MachineIngredientDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CurrentCapacityIngredient")
                        .HasColumnType("int");

                    b.Property<int?>("IngredientDAOId")
                        .HasColumnType("int");

                    b.Property<int?>("MachineDAOId")
                        .HasColumnType("int");

                    b.Property<int>("MaxCapacityIngredient")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientDAOId");

                    b.HasIndex("MachineDAOId");

                    b.ToTable("MachineIngredientDAOs");
                });

            modelBuilder.Entity("CoffeeShop.DAO.Impl.DAO.MachineServesDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int?>("DrinkDAOId")
                        .HasColumnType("int");

                    b.Property<int?>("MachineDAOId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrinkDAOId");

                    b.HasIndex("MachineDAOId");

                    b.ToTable("MachineServesDAOs");
                });

            modelBuilder.Entity("CoffeeShop.DAO.Impl.DAO.RecipeDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int?>("DrinkDAOId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrinkDAOId");

                    b.ToTable("RecipeDAOs");
                });

            modelBuilder.Entity("CoffeeShop.DAO.Impl.DAO.RecipeIngredientDAO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("IngredientDAOId")
                        .HasColumnType("int");

                    b.Property<int?>("RecipeDAOId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientDAOId");

                    b.HasIndex("RecipeDAOId");

                    b.ToTable("RecipeIngredientDAOs");
                });

            modelBuilder.Entity("CoffeeShop.DAO.Impl.DAO.DrinkDAO", b =>
                {
                    b.HasOne("CoffeeShop.DAO.Impl.DAO.MachineDAO", "MachineDAO")
                        .WithMany()
                        .HasForeignKey("MachineDAOId");
                });

            modelBuilder.Entity("CoffeeShop.DAO.Impl.DAO.MachineIngredientDAO", b =>
                {
                    b.HasOne("CoffeeShop.DAO.Impl.DAO.IngredientDAO", "IngredientDAO")
                        .WithMany()
                        .HasForeignKey("IngredientDAOId");

                    b.HasOne("CoffeeShop.DAO.Impl.DAO.MachineDAO", "MachineDAO")
                        .WithMany()
                        .HasForeignKey("MachineDAOId");
                });

            modelBuilder.Entity("CoffeeShop.DAO.Impl.DAO.MachineServesDAO", b =>
                {
                    b.HasOne("CoffeeShop.DAO.Impl.DAO.DrinkDAO", "DrinkDAO")
                        .WithMany()
                        .HasForeignKey("DrinkDAOId");

                    b.HasOne("CoffeeShop.DAO.Impl.DAO.MachineDAO", "MachineDAO")
                        .WithMany()
                        .HasForeignKey("MachineDAOId");
                });

            modelBuilder.Entity("CoffeeShop.DAO.Impl.DAO.RecipeDAO", b =>
                {
                    b.HasOne("CoffeeShop.DAO.Impl.DAO.DrinkDAO", "DrinkDAO")
                        .WithMany()
                        .HasForeignKey("DrinkDAOId");
                });

            modelBuilder.Entity("CoffeeShop.DAO.Impl.DAO.RecipeIngredientDAO", b =>
                {
                    b.HasOne("CoffeeShop.DAO.Impl.DAO.IngredientDAO", "IngredientDAO")
                        .WithMany()
                        .HasForeignKey("IngredientDAOId");

                    b.HasOne("CoffeeShop.DAO.Impl.DAO.RecipeDAO", "RecipeDAO")
                        .WithMany()
                        .HasForeignKey("RecipeDAOId");
                });
#pragma warning restore 612, 618
        }
    }
}
